#CheckFunctionExists
#CheckIncludeFile
#CheckIncludeFileCXX
#CheckIncludeFiles
#CheckLibraryExists
#CheckStructHasMember
#CheckSymbolExists
#CheckTypeSize
#CheckVariableExists


include(CheckFunctionExists)
include(CheckIncludeFile)
include(CheckIncludeFiles)
include(CheckLibraryExists)
include(CheckSymbolExists)
include(CheckStructHasMember)
include(CheckTypeSize)
include(CheckVariableExists)


set(AC_APPLE_UNIVERSAL_BUILD) 
set(ALIGNOF_GUINT32 4)
set(ALIGNOF_GUINT64 4)
set(ALIGNOF_UNSIGNED_LONG 4)
set(BROKEN_POLL)
set(CRAY_STACKSEG_END)
set(C_ALLOCA)
set(DISABLE_MEM_POOLS)
set(ENABLE_GC_FRIENDLY_DEFAULT)

set(ENABLE_NLS 1)
#set(ENABLE_SUBUNIT)
set(GETTEXT_PACKAGE \"glib20\")
set(GLIB_BINARY_AGE 3201)
set(GLIB_INTERFACE_AGE 1)
set(GLIB_LOCALE_DIR \"groot/glib/locale\")
set(GLIB_MAJOR_VERSION 2)
set(GLIB_MICRO_VERSION 1)
set(GLIB_MINOR_VERSION 32)
set(G_HAVE_INLINE 1)
set(G_HAVE___INLINE 1)
set(G_HAVE___INLINE__ 1)
set(G_VA_COPY va_copy)
set(G_VA_COPY_AS_ARRAY)

#set(HAVE_ALLOCA)
check_function_exists(alloca HAVE_ALLOCA)
check_include_files(alloca.h HAVE_ALLOCA_H)
check_include_files(arpa/nameser_compat.h HAVE_ARPA_NAMESER_COMPAT_H)
check_function_exists(atexit HAVE_ATEXIT)
check_include_files(attr/xattr.h HAVE_ATTR_XATTR_H)
check_function_exists(bind_textdomain_codeset HAVE_BIND_TEXTDOMAIN_CODESET)
check_function_exists(snprintf HAVE_C99_SNPRINTF)
check_function_exists(vsnprintf HAVE_C99_VSNPRINTF)

set(HAVE_CARBON)
check_function_exists(chown HAVE_CHOWN)
check_function_exists(clock_gettime HAVE_CLOCK_GETTIME)
set(HAVE_COCOA)
# Have nl_langinfo (CODESET)
set(HAVE_CODESET 1)
check_include_files(crt_externs.h HAVE_CRT_EXTERNS_H)
set(HAVE_DBUS1 1)
check_function_exists(dcgettext HAVE_DCGETTEXT)
check_include_files(dirent.h HAVE_DIRENT_H)
check_include_files(dlfcn.h HAVE_DLFCN_H)
#  Define to 1 if you don't have `vprintf' but do have `_doprnt.'
set(HAVE_DOPRNT)
set(HAVE_DOWHILE_MACROS 1)
set(HAVE_DTRACE)
check_function_exists(endmntent HAVE_ENDMNTENT)
check_function_exists(endservent HAVE_ENDSERVENT)
check_function_exists(eventfd HAVE_EVENTFD)

set(HAVE_FAM)
if (HAVE_FAM)
check_include_files(fam.h HAVE_FAM_H)
# Define if we have FAMNoExists in fam
set(HAVE_FAM_NO_EXISTS)
endif()

check_function_exists(fchmod HAVE_FCHMOD)
check_function_exists(fchown HAVE_FCHOWN)
check_function_exists(fdwalk HAVE_FDWALK)
check_include_files(float.h HAVE_FLOAT_H)
check_include_files(fstab.h HAVE_FSTAB_H)
check_function_exists(fsync HAVE_FSYNC)
check_function_exists(futex HAVE_FUTEX)
check_function_exists(getcwd HAVE_GETCWD)
check_function_exists(getc_unlocked HAVE_GETC_UNLOCKED)
check_function_exists(getfsstat HAVE_GETFSSTAT)
check_function_exists(getgrgid HAVE_GETGRGID)
check_function_exists(getmntent_r HAVE_GETMNTENT_R)

check_function_exists(getprotobyname_r HAVE_GETPROTOBYNAME_R)
check_function_exists(getpwuid HAVE_GETPWUID)
check_function_exists(gettext HAVE_GETTEXT)
check_function_exists(getvfsstat HAVE_GETVFSSTAT)
check_function_exists(gmtime_r HAVE_GMTIME_R)

#define to use system printf
set(HAVE_GOOD_PRINTF 1)
check_include_files(grp.h HAVE_GRP_H)
check_function_exists(hasmntopt HAVE_HASMNTOPT)
check_function_exists(if_nametoindex HAVE_IF_NAMETOINDEX)
check_function_exists(inotify_init1 HAVE_INOTIFY_INIT1)
set(HAVE_INT64_AND_I64)
# Define if you have the 'intmax_t' type in <stdint.h> or <inttypes.h>.
set(HAVE_INTMAX_T 1)
check_include_files(inttypes.h HAVE_INTTYPES_H)
set(HAVE_INTTYPES_H_WITH_UINTMAX 1)
check_type_size("struct ip_mreqn" IP_MREQN)
check_include_files(langinfo.h HAVE_LANGINFO_CODESET)
set(HAVE_LANGINFO_OUTDIGIT 1)
set(HAVE_LANGINFO_TIME 1)
check_function_exists(lchmod HAVE_LCHMOD)
check_function_exists(lchown HAVE_LCHOWN)
check_include_files(locale.h HAVE_LC_MESSAGES)
set(HAVE_LIBELF)
check_include_files(limits.h HAVE_LIMITS_H)
check_function_exists(link HAVE_LINK)
check_include_files(linux/magic.h HAVE_LINUX_MAGIC_H)
check_include_files(locale.h HAVE_LOCALE_H)
check_function_exists(localtime_r HAVE_LOCALTIME_R)
check_type_size("long double" LONG_DOUBLE)
check_type_size("long long" LONG_LONG)
set(HAVE_LONG_LONG_FORMAT 1)
check_function_exists(lstat HAVE_LSTAT)
check_include_files(malloc.h HAVE_MALLOC_H)
check_function_exists(memalign HAVE_MEMALIGN)
check_function_exists(memmem HAVE_MEMMEM)
check_function_exists(memmove HAVE_MEMMOVE)
check_include_files(memory.h HAVE_MEMORY_H)
check_function_exists(mmap HAVE_MMAP)
check_include_files(mntent.h HAVE_MNTENT_H)
check_include_files(ndir.h HAVE_NDIR_H)
check_include_files(netdb.h HAVE_NETDB_H)
set(HAVE_NETLINK 1)
check_function_exists(newlocale HAVE_NEWLOCALE)
check_function_exists(getgrgid_r HAVE_NONPOSIX_GETGRGID_R)
check_function_exists(getpwuid_r HAVE_NONPOSIX_GETPWUID_R)
check_function_exists(on_exit HAVE_ON_EXIT)
check_function_exists(pipe2 HAVE_PIPE2)
check_function_exists(poll HAVE_POLL)
check_function_exists(getgrgid_r HAVE_POSIX_GETGRGID_R)
check_function_exists(getpwuid_r HAVE_POSIX_GETPWUID_R)
check_function_exists(posix_memalign HAVE_POSIX_MEMALIGN)
check_function_exists(prlimit HAVE_PRLIMIT)
check_function_exists(pthread_attr_setstacksize HAVE_PTHREAD_ATTR_SETSTACKSIZE)
check_function_exists(pthread_condattr_setclock HAVE_PTHREAD_CONDATTR_SETCLOCK)
check_type_size(ptrdiff_t PTRDIFF_T)
check_include_files(pwd.h HAVE_PWD_H)
check_function_exists(readlink HAVE_READLINK)
check_include_files(sched.h HAVE_SCHED_H)

set(HAVE_SELINUX)
if (HAVE_SELINUX)
check_include_files(selinux/selinux.h HAVE_SELINUX_SELINUX_H)
endif()

check_function_exists(setenv HAVE_SETENV)
check_function_exists(setlocale HAVE_SETLOCALE)
check_function_exists(setmntent HAVE_SETMNTENT)
check_type_size(sig_atomic_t SIG_ATOMIC_T)
check_function_exists(snprintf HAVE_SNPRINTF)
check_function_exists(splice HAVE_SPLICE)
check_function_exists(statfs HAVE_STATFS)
check_function_exists(statvfs HAVE_STATVFS)
check_include_files(stddef.h HAVE_STDDEF_H)
check_include_files(stdint.h HAVE_STDINT_H)
# Define if <stdint.h> exists, doesn't clash with <sys/types.h>, and declares uintmax_t. 
set(HAVE_STDINT_H_WITH_UINTMAX 1)
check_include_files(stdlib.h HAVE_STDLIB_H)
check_function_exists(stpcpy HAVE_STPCPY)
check_function_exists(strcasecmp HAVE_STRCASECMP)
check_function_exists(strerror HAVE_STRERROR)
check_include_files(strings.h HAVE_STRINGS_H)
check_include_files(string.h HAVE_STRING_H)
check_function_exists(strlcpy HAVE_STRLCPY)
check_function_exists(strncasecmp HAVE_STRNCASECMP)
check_function_exists(strsignal HAVE_STRSIGNAL)
check_function_exists(strtod_l HAVE_STRTOD_L)
check_function_exists(strtoll_l HAVE_STRTOLL_L)
check_function_exists(strtoull_l HAVE_STRTOULL_L)

check_struct_has_member("struct dirent" d_type dirent.h HAVE_STRUCT_DIRENT_D_TYPE)
check_struct_has_member("struct statfs" f_bavail sys/statfs.h HAVE_STRUCT_STATFS_F_BAVAIL)
check_struct_has_member("struct statfs" f_fstypename sys/statfs.h HAVE_STRUCT_STATFS_F_FSTYPENAME)
check_struct_has_member("struct statvfs" f_basetype sys/statvfs.h HAVE_STRUCT_STATVFS_F_BASETYPE)
check_struct_has_member("struct statvfs" f_fstypename sys/statvfs.h HAVE_STRUCT_STATVFS_F_FSTYPENAME)
check_struct_has_member("struct stat" st_atimensec sys/stat.h HAVE_STRUCT_STAT_ST_ATIMENSEC)
check_struct_has_member("struct stat" st_atim.tv_nsec sys/stat.h HAVE_STRUCT_STAT_ST_ATIM_TV_NSEC)
check_struct_has_member("struct stat" st_blksize sys/stat.h HAVE_STRUCT_STAT_ST_BLKSIZE)
check_struct_has_member("struct stat" st_blocks sys/stat.h HAVE_STRUCT_STAT_ST_BLOCKS)
check_struct_has_member("struct stat" st_ctimensec sys/stat.h HAVE_STRUCT_STAT_ST_CTIMENSEC)
check_struct_has_member("struct stat" st_ctim.tv_nsec sys/stat.h HAVE_STRUCT_STAT_ST_CTIM_TV_NSEC)
check_struct_has_member("struct stat" st_mtimensec sys/stat.h HAVE_STRUCT_STAT_ST_MTIMENSEC)
check_struct_has_member("struct stat" st_mtim.tv_nsec sys/stat.h HAVE_STRUCT_STAT_ST_MTIM_TV_NSEC)
check_struct_has_member("struct tm" tm_gmtoff time.h HAVE_STRUCT_TM_TM_GMTOFF)
check_struct_has_member("struct tm" __tm_gmtoff time.h HAVE_STRUCT_TM___TM_GMTOFF)

check_function_exists(symlink HAVE_SYMLINK)
check_include_files(sys/dir.h HAVE_SYS_DIR_H)
check_include_files(sys/inotify.h HAVE_SYS_INOTIFY_H)
check_include_files(sys/mkdev.h HAVE_SYS_MKDEV_H)
check_include_files(sys/mntctl.h HAVE_SYS_MNTCTL_H)
check_include_files(sys/mnttab.h HAVE_SYS_MNTTAB_H)
check_include_files(sys/mount.h HAVE_SYS_MOUNT_H)
check_include_files(sys/ndir.h HAVE_SYS_NDIR_H)
check_include_files(sys/param.h HAVE_SYS_PARAM_H)
check_include_files(sys/poll.h HAVE_SYS_POLL_H)
check_include_files(sys/prctl.h HAVE_SYS_PRCTL_H)
check_include_files(sys/resource.h HAVE_SYS_RESOURCE_H)
check_include_files(sys/select.h HAVE_SYS_SELECT_H)
check_include_files(sys/statfs.h HAVE_SYS_STATFS_H)
check_include_files(sys/statvfs.h HAVE_SYS_STATVFS_H)
check_include_files(sys/stat.h HAVE_SYS_STAT_H)
check_include_files(sys/sysctl.h HAVE_SYS_SYSCTL_H)
check_include_files(sys/times.h HAVE_SYS_TIMES_H)
check_include_files(sys/time.h HAVE_SYS_TIME_H)
check_include_files(sys/types.h HAVE_SYS_TYPES_H)
check_include_files(sys/uio.h HAVE_SYS_UIO_H)
check_include_files(sys/vfstab.h HAVE_SYS_VFSTAB_H)
check_include_files(sys/vfs.h HAVE_SYS_VFS_H)
check_include_files(sys/vmount.h HAVE_SYS_VMOUNT_H)
check_include_files(sys/wait.h HAVE_SYS_WAIT_H)
check_include_files(sys/xattr.h HAVE_SYS_XATTR_H)
check_function_exists(timegm HAVE_TIMEGM)
check_include_files(unistd.h HAVE_UNISTD_H)
check_function_exists(printf HAVE_UNIX98_PRINTF)
check_function_exists(unsetenv HAVE_UNSETENV)
check_function_exists(uselocale HAVE_USELOCALE)
check_function_exists(utimes HAVE_UTIMES)
check_function_exists(valloc HAVE_VALLOC)
check_include_files(values.h HAVE_VALUES_H)
check_function_exists(vasprintf HAVE_VASPRINTF)
check_function_exists(vprintf HAVE_VPRINTF)
check_function_exists(vsnprintf HAVE_VSNPRINTF)
check_type_size(wchar_t WCHAR_T)
check_function_exists(wcslen HAVE_WCSLEN)
check_type_size(wint_t WINT_T)
set(HAVE_WORKING_BCOPY)
check_include_files(wspiapi.h HAVE_WSPIAPI_H)
set(HAVE_XATTR 1)
set(XATTR_NOFOLLOW)
check_include_files(xlocale.h HAVE_XLOCALE_H)
check_function_exists(_NSGetEnviron HAVE__NSGETENVIRON)

set(LT_OBJDIR)
set(NEED_ICONV_CACHE)
set(NO_FD_SET)
set(NO_MINUS_C_MINUS_O)
set(PACKAGE_BUGREPORT \"http://bugzilla.gnome.org/enter_bug.cgi?product=glib\")
set(PACKAGE_NAME \"glib\")
set(PACKAGE_STRING \"glib\ 2.32.1\")
set(PACKAGE_TARNAME \"glib\")
set(PACKAGE_URL \"\")
set(PACKAGE_VERSION \"2.32.1\")
set(POSIX_MEMALIGN_WITH_COMPLIANT_ALLOCS 1)
set(REALLOC_0_WORKS 1)
set(SANE_MALLOC_PROTOS)
check_type_size(char SIZEOF_CHAR)
check_type_size(int SIZEOF_INT)
check_type_size(long SIZEOF_LONG)
check_type_size("long long" SIZEOF_LONG_LONG)
check_type_size(short SIZEOF_SHORT)
check_type_size(size_t SIZEOF_SIZE_T)
check_type_size("void *" SIZEOF_VOID_P)
check_type_size(__int64 SIZEOF___INT64)

set(STACK_DIRECTION)
set(STATFS_ARGS 2)
set(STDC_HEADERS 1)
set(USE_LIBICONV_GNU)
set(USE_LIBICONV_NATIVE)
set(USE_STATFS 1)
set(USE_STATVFS)
set(USE_SYSTEM_PCRE)
set(WORDS_BIGENDIAN)

set(_FILE_OFFSET_BITS 64)
set(_GNU_SOURCE 1)
set(_LARGE_FILES)
set(_XOPEN_SOURCE)
set(_XOPEN_SOURCE_EXTENDED)
set(__EXTENSIONS__)
set(const)
set(intmax_t)
set(signed)
set(size_t)


configure_file(config.h.cmake.in config.h)
include_directories(${PROJECT_BINARY_DIR}/include)
